### ISSUE TITLE
KiCAD 7 Problems

### ISSUE THREAD

**Issue by kiranshila** [weirdgyn/viastitching#21]
I'm having some issues running this on kicad 7. Here is the traceback I'm getting.
```
Traceback (most recent call last):
  File "C:\Users/Kiran Shila/Documents/KiCad/7.0/scripting\plugins\viastitching\viastitching_dialog.py", line 453, in onProcessAction
    self.FillupArea()
  File "C:\Users/Kiran Shila/Documents/KiCad/7.0/scripting\plugins\viastitching\viastitching_dialog.py", line 365, in FillupArea
    if self.area.HitTestFilledArea(layer, p, 0):
  File "C:\Program Files\KiCad\7.0\bin\Lib\site-packages\pcbnew.py", line 13738, in HitTestFilledArea
    return _pcbnew.ZONE_HitTestFilledArea(self, aLayer, aRefPos, aAccuracy)
TypeError: in method 'ZONE_HitTestFilledArea', argument 3 of type 'VECTOR2I const &'
Additional information:
Wrong number or type of arguments for overloaded function 'ZONE_HitTestFilledArea'.
  Possible C/C++ prototypes are:
    ZONE::HitTestFilledArea(PCB_LAYER_ID,VECTOR2I const &,int) const
    ZONE::HitTestFilledArea(PCB_LAYER_ID,VECTOR2I const &) const
```
Any advise would be appreciated.

**Comment by weirdgyn** [comment]
Fixed with 4d2c5232ada59f02ff69e171adeefe0624064be0 commit... give it a check
