### ISSUE TITLE
Error in KiCad 8

### ISSUE THREAD

**Issue by boromyr** [weirdgyn/viastitching#27]
```py
---------------------------
Exception on python action plugin code
---------------------------
Traceback (most recent call last):

  File "D:\Users/PC/Documents/KiCad/8.0/scripting\plugins\com_github_jsreynaud_kicad-action-scripts\ViaStitching\FillAreaAction.py", line 88, in Run
    fill.Run()

  File "D:\Users/PC/Documents/KiCad/8.0/scripting\plugins\com_github_jsreynaud_kicad-action-scripts\ViaStitching\FillArea.py", line 590, in Run
    board_edge.Deflate(int(b_clearance), int(12),  SHAPE_POLY_SET.ROUND_ALL_CORNERS)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: type object 'SHAPE_POLY_SET' has no attribute 'ROUND_ALL_CORNERS'

```
After starting the generation of the 'vias' I get this error message.

**Comment by weirdgyn** [comment]
Closing because the traceback is from com_github_jsreynaud_kicad-action-scripts/ViaStitching (FillAreaAction.py / FillArea.py), which is a different plugin and repository. Please report this to the kicad-action-scripts maintainers.
